version: '2'
services:
  sonarqube:
    build: ./sonar
    ports:
      - "9000:9000"
      - "9002:9002"
    environment:
      # configure connection to MySQL
      # TODO for some reason sonar.properties not working.
      - SONARQUBE_JDBC_USERNAME=sonaruser
      - SONARQUBE_JDBC_PASSWORD=sonaruser
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqube_db_1:3306/sonarqubedb?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance
    volumes:
      - /opt/sonarqube_data/sonarqube_conf:/opt/sonarqube/conf
      - /opt/sonarqube_data/sonarqube_data:/opt/sonarqube/data
      - /opt/sonarqube_data/sonarqube_extensions:/opt/sonarqube/extensions
      - /opt/sonarqube_data/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

    # allow db container to be provisioned first
    # make db container accessible from sonarqube container
    links:
      - db
  db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sonaruser
      - MYSQL_PASSWORD=sonaruser
      - MYSQL_DATABASE=sonarqubedb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      # MySQL Configuration is external
      - "./mysql/conf.d:/etc/mysql/conf.d:ro"
      # MySQL Data is external to Container
      - "/opt/mysql_data:/var/lib/mysql"
